name: "CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: password
    env:
      RACK_ENV: test
      DATABASE_URL: "postgres://test_user:password@localhost:5432/test_db"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
      - uses: actions/setup-node@v4
        with:
          node-version: 21
      - name: Install Node dependencies
        run: npm ci
      - name: Build React app
        run: npm run build
      - name: Set up database schema
        run: bundle exec rake db:schema:load
      - name: Run tests
        run: bundle exec rake
